project:
  type: website
  output-dir: docs

website:
<<<<<<< Updated upstream
  title: "Doga's Analytics Lab"
=======
  title: "DoÄŸa's Analytics Lab"
>>>>>>> Stashed changes
  navbar:
    search: true
    left:
      - text: Homepage
        href: index.qmd
      - text: About Me
        href: about.qmd
      - text: Posts
        href: posts.qmd
      - text: "EMU430 Coursework"
        menu:
          - text: My Assignments
            href: assignments.qmd
          - text: Data_Ciphers Project
            href: project.qmd
            
    tools:
      - icon: github
        href: https://github.com
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
<<<<<<< Updated upstream
        href: https://www.linkedin.com/in/doga-oral/
=======
        href: https://www.linkedin.com
>>>>>>> Stashed changes

  sidebar:
    - title: "Assignments"
      style: "docked"
      search: true
      contents:
        - assignments.qmd
        - assignments/assignment-1.qmd
        - assignments/assignment-2.qmd  
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU 430 - Fall 2023" 
    border: true
format:
  html: 
    toc: true
    toc-location: left
    theme: 
      light: pulse
      dark: superhero
    css: styles.css

editor: visual
